spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webflux-security
    username: demo
    password: 1234
  jackson:
    default-property-inclusion: non-null
    visibility:
      field: any
